# Generated by Django 4.1.3 on 2022-12-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=100)),
                ('bike_model', models.CharField(max_length=100)),
                ('bike_cc', models.IntegerField()),
                ('bike_average', models.IntegerField()),
            ],
        ),
    ]
