# Generated by Django 4.1.3 on 2022-12-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_roll', models.CharField(max_length=100)),
                ('employee_age', models.IntegerField()),
                ('employee_salary', models.IntegerField()),
            ],
        ),
    ]
